# Generated by Django 6.2.dev20260611202632 on 2026-06-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
