# Generated by Django 6.2.dev20260611202632 on 2026-06-15 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
