# Generated by Django 6.0.6 on 2026-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=15)),
                ('description', models.TextField(max_length=100)),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='')),
                ('casts', models.ManyToManyField(to='movie.cast')),
                ('categories', models.ManyToManyField(to='movie.category')),
            ],
        ),
    ]
